# Numpy

In [1]:
import numpy as np

In [3]:
array1 = np.array([1,2,3])
print('array1 type :', type(array1))
print('array1 array 형태 :', array1.shape)

array1 type : <class 'numpy.ndarray'>
array1 array 형태 : (3,)


In [6]:
array2 = np.array([[1,2,3], [2,3,4]])
print('array1 type :', type(array2))
print('array1 array 형태 :', array2.shape)

array1 type : <class 'numpy.ndarray'>
array1 array 형태 : (2, 3)


In [7]:
array3 = np.array([[1,2,3]])
print('array1 type :', type(array3))
print('array1 array 형태 :', array3.shape)

array1 type : <class 'numpy.ndarray'>
array1 array 형태 : (1, 3)


In [8]:
print(f'array1: {array1.ndim}차원, array2: {array2.ndim}차원, array3: {array3.ndim}차원')

array1: 1차원, array2: 2차원, array3: 2차원


### arange(), zeros(), ones()

In [16]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)
type(sequence_array)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


numpy.ndarray

In [19]:
zero_array = np.zeros((2,3), dtype='int32')
print(zero_array, zero_array.dtype)

[[0 0 0]
 [0 0 0]] int32


### reshape()

In [30]:
array1 = np.arange(3,11, dtype='int32')
print(array1)
array1.reshape(-1,4)

[ 3  4  5  6  7  8  9 10]


array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [33]:
np.array([[[1,2], [3,4]], [[5,6], [7,8]]]).reshape(-1,2).reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### sort(), argsort()

In [43]:
org_array = np.array([[3,1,9,5], [2,1,4,3]])
print('원본행렬 :', org_array)

원본행렬 : [[3 1 9 5]
 [2 1 4 3]]


In [48]:
sort_array1 = np.sort(org_array, axis=0)
print(sort_array1)

[[2 1 4 3]
 [3 1 9 5]]


In [50]:
name_array = ['j', 'm','s','k','e']
score_array = [78, 95, 84, 98, 88]

In [65]:
idx = np.argsort(score_array)[::-1]
type(idx)

numpy.ndarray

# Pandas

In [67]:
import pandas as pd

In [70]:
titanic_df = pd.read_csv('./titanic_train.csv')

In [74]:
titanic_df.head(3)
# print('titanic 변수 type : ', type(titanic_df))

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [75]:
print('titanic_df의 shape:', titanic_df.shape)

titanic_df의 shape: (891, 12)


In [76]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [77]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [79]:
titanic_df['Pclass'].head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

### ndarray, list, dict ==> dataframe 변환

In [86]:
col_name1 = ['col1']
list1 = [1,2,3]
array1 = np.array(list1)
print('array1 shape:', array1.shape)

# list를 이용하여 dataframe 생성
df_list1 = pd.DataFrame(list1, columns=col_name1)
print(df_list1)
# array를 이용하여 dataframe 생성
df_array1 = pd.DataFrame(array1, columns = col_name1)
print(df_array1)

array1 shape: (3,)
   col1
0     1
1     2
2     3
   col1
0     1
1     2
2     3


In [87]:
# dict를 이용하여 dataframe 생성
dict = {'col1': [1,11], 'col2':[2,22], 'col3':[3,33]}
df_dict = pd.DataFrame(dict)
df_dict

col1  col2  col3
0     1     2     3
1    11    22    33

In [94]:
print(df_dict.values.tolist())
print(df_dict.to_dict('list'))

[[1, 2, 3], [11, 22, 33]]
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


In [100]:
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)
print(titanic_df.head(3))

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S


In [103]:
titanic_df.index[:5].values

array([0, 1, 2, 3, 4], dtype=int64)

In [104]:
titanic_df.index.values[:5]

array([0, 1, 2, 3, 4], dtype=int64)

In [105]:
titanic_df.index[6]

6