# Numpy

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
print('array1 type :', type(array1))
print('array1 array 형태 :', array1.shape)

array1 type : <class 'numpy.ndarray'>
array1 array 형태 : (3,)


In [3]:
array2 = np.array([[1,2,3], [2,3,4]])
print('array1 type :', type(array2))
print('array1 array 형태 :', array2.shape)

array1 type : <class 'numpy.ndarray'>
array1 array 형태 : (2, 3)


In [4]:
array3 = np.array([[1,2,3]])
print('array1 type :', type(array3))
print('array1 array 형태 :', array3.shape)

array1 type : <class 'numpy.ndarray'>
array1 array 형태 : (1, 3)


In [5]:
print(f'array1: {array1.ndim}차원, array2: {array2.ndim}차원, array3: {array3.ndim}차원')

array1: 1차원, array2: 2차원, array3: 2차원


### arange(), zeros(), ones()

In [6]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)
type(sequence_array)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


numpy.ndarray

In [7]:
zero_array = np.zeros((2,3), dtype='int32')
print(zero_array, zero_array.dtype)

[[0 0 0]
 [0 0 0]] int32


### reshape()

In [8]:
array1 = np.arange(3,11, dtype='int32')
print(array1)
array1.reshape(-1,4)

[ 3  4  5  6  7  8  9 10]


array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [9]:
np.array([[[1,2], [3,4]], [[5,6], [7,8]]]).reshape(-1,2).reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### sort(), argsort()

In [10]:
org_array = np.array([[3,1,9,5], [2,1,4,3]])
print('원본행렬 :', org_array)

원본행렬 : [[3 1 9 5]
 [2 1 4 3]]


In [11]:
sort_array1 = np.sort(org_array, axis=0)
print(sort_array1)

[[2 1 4 3]
 [3 1 9 5]]


In [12]:
name_array = ['j', 'm','s','k','e']
score_array = [78, 95, 84, 98, 88]

In [13]:
idx = np.argsort(score_array)[::-1]
type(idx)

numpy.ndarray

# Pandas

In [14]:
import pandas as pd

In [15]:
titanic_df = pd.read_csv('./titanic_train.csv')

In [16]:
titanic_df.head(3)
# print('titanic 변수 type : ', type(titanic_df))

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [17]:
print('titanic_df의 shape:', titanic_df.shape)

titanic_df의 shape: (891, 12)


In [18]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [19]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [20]:
titanic_df['Pclass'].head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

### ndarray, list, dict ==> dataframe 변환

In [21]:
col_name1 = ['col1']
list1 = [1,2,3]
array1 = np.array(list1)
print('array1 shape:', array1.shape)

# list를 이용하여 dataframe 생성
df_list1 = pd.DataFrame(list1, columns=col_name1)
print(df_list1)
# array를 이용하여 dataframe 생성
df_array1 = pd.DataFrame(array1, columns = col_name1)
print(df_array1)

array1 shape: (3,)
   col1
0     1
1     2
2     3
   col1
0     1
1     2
2     3


In [22]:
# dict를 이용하여 dataframe 생성
dict = {'col1': [1,11], 'col2':[2,22], 'col3':[3,33]}
df_dict = pd.DataFrame(dict)
df_dict

col1  col2  col3
0     1     2     3
1    11    22    33

In [23]:
print(df_dict.values.tolist())
print(df_dict.to_dict('list'))

[[1, 2, 3], [11, 22, 33]]
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


In [24]:
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)
print(titanic_df.head(3))

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S


In [25]:
titanic_df.index[:5].values

array([0, 1, 2, 3, 4], dtype=int64)

In [26]:
titanic_df.index.values[:5]

array([0, 1, 2, 3, 4], dtype=int64)

In [27]:
titanic_df.index[6]

6

In [35]:
series_fair = titanic_df['Fare']

In [39]:
ttn_rst_df = titanic_df.reset_index(inplace = False)
ttn_rst_df

index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0        0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1        1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2        2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
3        3            4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S
4        4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S
..     ...          ...       ...     ...             ...     ...   ...    ...    ...             ...      ...   ...      ...
886    886          887         0       2  Montvila, R...    male  27.0      0      0          211536  13.0000   NaN        S
887    887          888         1       1  Graham, Mis...  female  19.0      0      0          112053  30.0000   B42        S
888    888          889         0       3  Johnston, M...  female   NaN      1      2      W./C. 6607  23.4500   NaN        S
889    889          890         1       1  Behr, Mr. K...    male  26.0      0      0          111369  30.0000  C148        C
890    890          891         0       3  Dooley, Mr....    male  32.0      0      0          370376   7.7500   NaN        Q

[891 rows x 13 columns]

In [42]:
titanic_df['Pclass'].value_counts().reset_index(inplace=False)

index  Pclass
0      3     491
1      1     216
2      2     184

# 데이터 셀렉션 및 필터링

- ix, iloc, loc

In [49]:
titanic_df[['Fare', 'Pclass']]

Fare  Pclass
0     7.2500       3
1    71.2833       1
2     7.9250       3
3    53.1000       1
4     8.0500       3
..       ...     ...
886  13.0000       2
887  30.0000       1
888  23.4500       3
889  30.0000       1
890   7.7500       3

[891 rows x 2 columns]

In [44]:
titanic_df[0:2]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C

In [51]:
titanic_df[ titanic_df['Pclass'] == 3 ]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0              1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
2              3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
4              5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S
5              6         0       3  Moran, Mr. ...    male   NaN      0      0          330877   8.4583   NaN        Q
7              8         0       3  Palsson, Ma...    male   2.0      3      1          349909  21.0750   NaN        S
..           ...       ...     ...             ...     ...   ...    ...    ...             ...      ...   ...      ...
882          883         0       3  Dahlberg, M...  female  22.0      0      0            7552  10.5167   NaN        S
884          885         0       3  Sutehall, M...    male  25.0      0      0  SOTON/OQ 39...   7.0500   NaN        S
885          886         0       3  Rice, Mrs. ...  female  39.0      0      5          382652  29.1250   NaN        Q
888          889         0       3  Johnston, M...  female   NaN      1      2      W./C. 6607  23.4500   NaN        S
890          891         0       3  Dooley, Mr....    male  32.0      0      0          370376   7.7500   NaN        Q

[491 rows x 12 columns]

In [57]:
titanic_df.loc[0, ]

PassengerId                 1
Survived                    0
Pclass                      3
Name           Braund, Mr....
Sex                      male
Age                        22
SibSp                       1
Parch                       0
Ticket              A/5 21171
Fare                     7.25
Cabin                     NaN
Embarked                    S
Name: 0, dtype: object

## 정렬, Aggregation 함수, GroupBy 적용

- DataFrame, Series 의 정렬: sort_value( by = Col, ascending = False, inplace = False )
- Aggregation 함수: min(), max(), sum(), count(), mean() ...
- groupby( by = Col )

In [70]:
titanic_df.sort_values(by = ['Pclass', 'Name'], ascending = False)

PassengerId  Survived  Pclass            Name     Sex    Age  SibSp  Parch    Ticket      Fare    Cabin Embarked
868          869         0       3  van Melkebe...    male    NaN      0      0    345777    9.5000      NaN        S
153          154         0       3  van Billiar...    male  40.50      0      2  A/5. 851   14.5000      NaN        S
282          283         0       3  de Pelsmaek...    male  16.00      0      0    345778    9.5000      NaN        S
286          287         1       3  de Mulder, ...    male  30.00      0      0    345774    9.5000      NaN        S
559          560         1       3  de Messemae...  female  36.00      1      0    345572   17.4000      NaN        S
..           ...       ...     ...             ...     ...    ...    ...    ...       ...       ...      ...      ...
460          461         1       1  Anderson, M...    male  48.00      0      0     19952   26.5500      E12        S
498          499         0       1  Allison, Mr...  female  25.00      1      2    113781  151.5500  C22 C26        S
297          298         0       1  Allison, Mi...  female   2.00      1      2    113781  151.5500  C22 C26        S
305          306         1       1  Allison, Ma...    male   0.92      1      2    113781  151.5500  C22 C26        S
730          731         1       1  Allen, Miss...  female  29.00      0      0     24160  211.3375       B5        S

[891 rows x 12 columns]

In [69]:
titanic_df[['Name','Pclass']].count()

Name      891
Pclass    891
dtype: int64

### groupby 함수( -> 객체 반환 ) + aggregation 함수

In [76]:
titanic_df.groupby(by = 'Pclass')

In [78]:
titanic_df.groupby(by='Pclass')[['PassengerId', 'Survived']].count()

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [79]:
titanic_df.groupby('Pclass').agg(['max','min'])

PassengerId     Survived                Name                   Sex           Age       SibSp     Parch          Ticket              Fare     
               max min      max min             max             min   max     min   max   min   max min   max min         max     min       max  min
Pclass                                                                                                                                              
1              890   2        1   0  Young, Miss...  Allen, Miss...  male  female  80.0  0.92     3   0     4   0   WE/P 5735  110152  512.3292  0.0
2              887  10        1   0  del Carlo, ...  Abelson, Mr...  male  female  70.0  0.67     3   0     3   0   W/C 14208   11668   73.5000  0.0
3              891   1        1   0  van Melkebe...  Abbing, Mr....  male  female  74.0  0.42     8   0     6   0  W./C. 6609   12460   69.5500  0.0

In [80]:
titanic_df.groupby('Pclass').agg({'Age':'max', 'SibSp':'sum', 'Fare':'mean'})

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

### 결손 데이터 처리하기

- 결손 데이터 확인: isna()
- NaN 값을 다른 값으로 대체: fillna()

In [87]:
# True = 1, False = 0 을 이용하여 결측치 갯수 파악
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [89]:
titanic_df['Cabin'].fillna('C000')

0      C000
1       C85
2      C000
3      C123
4      C000
       ... 
886    C000
887     B42
888    C000
889    C148
890    C000
Name: Cabin, Length: 891, dtype: object

### apply lambda 식으로 데이터 가공

- lambda? 함수의 선언과 함수 내 처리를 한줄의 식으로 쉽게 변환하는 식
( 여러 개의 값을 입력 인자로 사용해야 할 경우에는 보통 map(f, iterable) 함수를 결합 )

In [90]:
titanic_df['Name'].apply(lambda x: len(x))

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [97]:
titanic_df['Age'].apply(lambda x: 'Child' if x<=15 else( 'Elderly' if x>=61 else 'Adult' )).value_counts()

Adult      786
Child       83
Elderly     22
Name: Age, dtype: int64